q2: prog.o rotate.o binary.o
	gcc -ansi -Wall -g prog.o rotate.o binary.o -o q2
prog.o: prog.c
	gcc -c -Wall prog.c -o prog.o
rotate.o: rotate.c
	gcc -c -Wall rotate.c -o rotate.o
binary.o: binary.c
	gcc -c -Wall binary.c -o binary.o
